[package]
name = "dagr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bollard = "0.11.1"
daggy = "0.8.0"
futures-util = "0.3.19"
tokio = { version = "1.16.1", features = ["full"] }
